### ISSUE TITLE
Reload Lang Resources?

### ISSUE THREAD

**Issue by DeadSlayer54** [PowerCraft/2.0#1]
I got the file and the powercraft folder in a folder called 'PowerCraft' (it was originally installed as a .rar but the 'p' hotkey didn't work that way and changing it to regular folder fixed that issue), but when I attempt to install modules it says 'Error reload lang resources", twice each attempt. Any tips on how I could fix this?

**Comment by DeadSlayer54** [comment]
Weird thing, clicking the 'all' option and installing them, though producing the same error (multiplied tremendously as it's twice per module), actually followed through with the installations. It is now running fine, where installing them individually (before I realized there was an 'all' option) did not produce such results.
So now that it works, I guess it works, but I'm curious about the error simply cause I'm a curious fella.

**Comment by DannikInfo** [comment]
I know about the error reloading resources, I will fix it in the next update of the launcher, I have not seen the rest, but I think it will be fixed too :)

**Comment by DannikInfo** [comment]
This error is only related to the graphical interface, modules are installed both one at a time and in a package, language resources are loaded after restarting the game, so there is no particular need to restart them after installation.

**Comment by TheDeviantCrafter** [comment]
This is still an issue in 0.1.0B. I get the error reloading resources bug, but the modules install correctly.

**Comment by DannikInfo** [comment]
due to lack of time, I still cannot complete the update, but this error has been fixed. 
p.s. most likely I will finish it in January, I think updates will come out only in winter and summer
